Repository Solvro/mobile-topwr, pull requests merged in 2024-09, with the labels that each got.

#177 Feat/ add wiredash feedback form
  assets/animations/bug.json
  build.yaml
  example.env
  lib/api_base/directus_assets_url.dart
  lib/api_base/gql_client_provider.dart
  lib/api_base/ttl/local_timestamp_repository.dart
  lib/config/env.dart
  lib/config/ui_config.dart
  lib/config/wiredash.dart
  lib/features/analytics/show_feedback_tile.dart
  lib/features/guide_view/guide_view.dart
  lib/features/parkings_view/api_client/iparking_client.dart
  lib/l10n/app_pl.arb
  lib/main.dart
  pubspec.yaml
Labels: enhancement

#180 feat: add android adaptive icon
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  pubspec.yaml
Labels: enhancement

#193 feat/ add favorite parkings feature
  lib/api_base/ttl/local_timestamp_repository.dart
  lib/config/shared_prefs.dart
  lib/features/parkings_view/repository/local_fav_parking_repository.dart
  lib/features/parkings_view/widgets/parking_favourite.dart
  lib/features/parkings_view/widgets/parking_wide_tile_card.dart
  pubspec.yaml
Labels: enhancement

#187 Feat/ add days to semester mode
  lib/features/academic_calendar/utils/counter_digits.dart
  lib/features/academic_calendar/utils/localize_academic_day.dart
  lib/features/academic_calendar/utils/localize_counter_message.dart
  lib/features/academic_calendar/widgets/countdown_widget/exam_session_countdown.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#195 Feat/place fav parking on top of parkings list
  lib/features/parkings_view/repository/parkings_repository.dart
Labels: enhancement

#206 Feat/ animate parkings tiles
  lib/config/map_view_config.dart
  lib/features/bottom_scroll_sheet/data_list.dart
  lib/features/map_view/controllers/controllers_set.dart
  pubspec.yaml
Labels: enhancement

#208 refactor/replace dashes with arrows trend and fix layout
  lib/config/ui_config.dart
  lib/features/parking_chart/parking_chart.dart
  lib/features/parkings_view/models/parking.dart
  lib/features/parkings_view/widgets/parking_wide_tile_card.dart
Labels: bug, enhancement

#207 Feat/ add remote cache flushing
  lib/api_base/cache/remote_flush/business/flush_cache_use_cases.dart
  lib/api_base/cache/remote_flush/data/getRemoteCacheRef.graphql
  lib/api_base/cache/remote_flush/data/local_cache_ref_number_repo.dart
  lib/api_base/cache/remote_flush/data/remote_cache_ref_number_repo.dart
  lib/api_base/cache/remote_flush/presentation/flush_cache_remotely_widget.dart
  lib/api_base/cache/ttl/local_timestamp_repository.dart
  lib/api_base/cache/ttl/ttl_service.dart
  lib/api_base/cache/ttl/ttl_timestamp.dart
  lib/api_base/query_adapter.dart
  lib/api_base/schema.graphql
  lib/config/ttl_config.dart
  lib/features/offline_messages/widgets/grapgql_offline_message.dart
  lib/main.dart
Labels: enhancement

#218 #213 - fix tags loading view - fix
  lib/config/ui_config.dart
  lib/features/science_clubs_filters/widgets/chips_loading.dart
Labels: bug

#219 Feat/remove slide tab bar transitions
  lib/config/transitions.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/navigation_controller.dart
  lib/features/navigator/utils/tab_bar_transition.dart
Labels: enhancement

#220 Feat/new map solution
  ios/Runner/AppDelegate.swift
  lib/config/map_view_config.dart
  lib/features/bottom_scroll_sheet/map_view_pop_behaviour.dart
  lib/features/buildings_view/building_tile.dart
  lib/features/buildings_view/buildings_view.dart
  lib/features/buildings_view/controllers.dart
  lib/features/buildings_view/model/building_model.dart
  lib/features/map_view/controllers/active_map_marker_cntrl.dart
  lib/features/map_view/controllers/controllers_set.dart
  lib/features/map_view/controllers/map_controller.dart
  lib/features/map_view/utils/google_maps_link_utils.dart
  lib/features/map_view/utils/location_permission_status_provider.dart
  lib/features/map_view/utils/map_marker_utils.dart
  lib/features/map_view/widgets/map_atrribution.dart
  lib/features/map_view/widgets/map_config.dart
  lib/features/map_view/widgets/map_widget.dart
  lib/features/map_view/widgets/markers_layer.dart
  lib/features/map_view/widgets/toolbar.dart
  lib/features/my_location_button/data/location_permission_status_provider.dart
  lib/features/my_location_button/presentation/is_following_controller.dart
  lib/features/my_location_button/presentation/my_loc_button.dart
  lib/features/my_location_button/presentation/my_loc_layer.dart
  lib/features/navigator/app_router.dart
  lib/features/parkings_view/controllers.dart
  lib/features/parkings_view/models/parking.dart
  lib/features/parkings_view/parkings_view.dart
  lib/features/splash_screen/splash_screen.dart
  lib/features/splash_screen/splash_screen_controller.dart
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#224 feat: add shimmer effect on about us view
  lib/features/about_us_view/about_us_view.dart
Labels: enhancement

#231 #230 - replace decimal numbers with integers at parking's page & make sure that free slots are always >= 0
  lib/features/parking_chart/widgets/chart_widget.dart
  lib/features/parkings_view/models/parking.dart
  lib/features/parkings_view/widgets/parking_wide_tile_card.dart
Labels: enhancement

#229 #221 - add cache support for map tiles
  lib/config/map_view_config.dart
  lib/features/map_view/widgets/map_widget.dart
  pubspec.yaml
Labels: enhancement

#248 fix: add small padding to logos
  lib/config/ui_config.dart
  lib/features/departments_view/widgets/department_card.dart
Labels: bug, enhancement, design

#255 Fix/add padding to right scrolls
  lib/features/home_view/widgets/buildings_section/buildings_section.dart
  lib/features/home_view/widgets/departments_section/departments_section.dart
  lib/features/home_view/widgets/news_section.dart
  lib/features/home_view/widgets/paddings.dart
  lib/features/home_view/widgets/parkings_section.dart
  lib/features/home_view/widgets/science_clubs_section.dart
Labels: bug

#259 feature: add tooltip widget with config
  lib/config/ui_config.dart
  lib/features/parkings_view/widgets/parking_wide_tile_card.dart
  lib/l10n/app_pl.arb
  lib/widgets/my_tooltip.dart
Labels: enhancement

#232 fix/overflow-in-sci-clubs-card
  lib/features/science_clubs_view/widgets/ensure_visible_tags.dart
  pubspec.yaml
Labels: bug
