Repository Solvro/mobile-topwr, pull requests merged in 2024-10, with the labels that each got.

#271 refactor/move-about-us-KN-links-above-team
  lib/features/about_us_view/about_us_view.dart
Labels: enhancement

#281 feat: add guide info about development
  lib/features/guide_view/guide_view.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#284 Fix/ about us freeze after scroll on open
  lib/features/about_us_view/about_us_view.dart
  lib/features/about_us_view/widgets/team_section.dart
Labels: bug

#291 Feat/ add verified checkmark to science clubs in all other places
  lib/config/ui_config.dart
  lib/features/department_detail_view/widgets/science_clubs_section.dart
  lib/features/home_view/widgets/science_clubs_section.dart
  lib/features/science_clubs_view/widgets/science_club_card.dart
  lib/widgets/big_preview_card.dart
  lib/widgets/dual_text_max_lines.dart
Labels: enhancement

#293 Feat/add checmark in sci club detail view
  lib/config/ui_config.dart
  lib/features/department_detail_view/widgets/science_clubs_section.dart
  lib/features/home_view/widgets/science_clubs_section.dart
  lib/features/science_club_detail_view/repository/getScienceClubDetails.graphql
  lib/features/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_clubs_view/widgets/science_club_card.dart
Labels: enhancement

#294 Feat/ add app's streak counter
  lib/config/shared_prefs.dart
  lib/features/app_streak/business/get_days_use_case.dart
  lib/features/app_streak/data/last_entry_repo.dart
  lib/features/app_streak/data/streak_start_repo.dart
  lib/features/app_streak/data/timstamp_repo_mixin.dart
  lib/features/app_streak/presentation/app_streak_counter.dart
  lib/features/home_view/home_view.dart
  lib/features/home_view/keep_alive_home_view_providers.dart
  lib/l10n/app_pl.arb
  lib/utils/timestamp.dart
Labels: enhancement

#297 feat/add-shadows-to-trend-arrow
  lib/features/parkings_view/widgets/parking_wide_tile_card.dart
Labels: enhancement

#299 fix/map-rotating-when-zooming
  lib/config/map_view_config.dart
  lib/features/map_view/widgets/map_widget.dart
Labels: enhancement

#306 Fix / unknown trend on parking view
  .fvm/flutter_sdk
  .fvm/fvm_config.json
  .github/workflows/lint_and_format.yml
  ios/Runner.xcodeproj/project.pbxproj
  lib/features/about_us_view/utils/html_util_extensions.dart
  lib/features/bottom_nav_bar/bottom_nav_bar.dart
  lib/features/bottom_scroll_sheet/drag_handle.dart
  lib/features/navigator/root_view.dart
  lib/features/navigator/utils/android_pop_bug_workaround.dart
  lib/features/parking_chart/chart_elements/chart_line.dart
  lib/features/parking_chart/parking_chart.dart
  lib/features/parkings_view/models/parking.dart
  lib/features/parkings_view/widgets/parking_wide_tile_card.dart
  lib/theme/hex_color.dart
  lib/widgets/search_box.dart
  pubspec.yaml
Labels: bug

#345 #286 feat add in app review
  lib/config/shared_prefs.dart
  lib/features/in_app_review/business/in_app_rating_service.dart
  lib/features/in_app_review/business/in_app_rating_service_provider.dart
  lib/features/in_app_review/in_app_review.dart
  lib/features/science_clubs_filters/widgets/apply_filters_button.dart
  lib/main.dart
  lib/utils/shared_prefs_extensions.dart
  pubspec.yaml
Labels: enhancement

#347 feat: handle in app deep links
  lib/config/url_config.dart
  lib/features/navigator/navigation_controller.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/utils/launch_url_util.dart
Labels: enhancement

#351 Feat/ animate maps camera
  analysis_options.yaml
  lib/features/bottom_scroll_sheet/data_list.dart
  lib/features/bottom_scroll_sheet/map_view_pop_behaviour.dart
  lib/features/buildings_view/building_tile.dart
  lib/features/buildings_view/buildings_view.dart
  lib/features/buildings_view/controllers.dart
  lib/features/map_view/controllers/controllers_set.dart
  lib/features/map_view/controllers/map_controller.dart
  lib/features/map_view/widgets/load_animated_controller.dart
  lib/features/map_view/widgets/map_widget.dart
  lib/features/parkings_view/controllers.dart
  lib/features/parkings_view/parkings_view.dart
  lib/features/parkings_view/widgets/parking_tile.dart
  pubspec.yaml
Labels: enhancement

#354 Fix: fix chart labels
  lib/features/parking_chart/chart_elements/labels_left.dart
Labels: bug

#353 Chore: hide streak counter from user
  lib/features/app_streak/business/get_days_use_case.dart
  lib/features/app_streak/presentation/app_streak_counter.dart
  lib/features/home_view/home_view.dart
  lib/utils/datetime_utils.dart
Labels: chore

#352 Feat/add app changelog for user
  lib/api_base/schema.graphql
  lib/config/ttl_config.dart
  lib/features/app_changelog/app_changelog.dart
  lib/features/app_changelog/repository/changelog_repository.dart
  lib/features/app_changelog/repository/get_changelog.graphql
  lib/features/app_changelog/repository/local_changelog_repository.dart
  lib/features/app_changelog/show_changelog.dart
  lib/features/app_changelog/update_changelog_wrapper.dart
  lib/features/app_changelog/widgets/app_changelog_header.dart
  lib/features/app_changelog/widgets/app_changelog_list.dart
  lib/features/navigator/root_view.dart
  lib/features/offline_messages/messages_config.dart
  lib/l10n/app_pl.arb
  lib/theme/app_text_theme.dart
  lib/theme/typography.dart
Labels: enhancement
