Repository Solvro/mobile-topwr, pull requests merged in 2024-11, with the labels that each got.

#392 Feat/add sks people counter
  example.env
  lib/config/env.dart
  lib/config/ui_config.dart
  lib/features/sks_people_live/data/api_client/sks_client.dart
  lib/features/sks_people_live/data/models/sks_user_data.dart
  lib/features/sks_people_live/data/repository/latest_sks_user_data_repo.dart
  lib/features/sks_people_live/presentation/sks_app_bar.dart
  lib/features/sks_people_live/presentation/widgets/sks_user_data_button.dart
Labels: enhancement

#387 SKS Menu
  lib/config/ui_config.dart
  lib/features/home_view/widgets/parkings_section.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/features/sks-menu/data/models/dish_category_enum.dart
  lib/features/sks-menu/data/models/sks_menu_data.dart
  lib/features/sks-menu/data/repository/sks_menu_repository.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
  lib/features/sks-menu/presentation/widgets/sks_menu_data_source_link.dart
  lib/features/sks-menu/presentation/widgets/sks_menu_header.dart
  lib/features/sks-menu/presentation/widgets/sks_menu_section.dart
  lib/features/sks-menu/presentation/widgets/sks_menu_tiles.dart
  lib/features/sks_people_live/data/api_client/sks_client.dart
  lib/features/sks_people_live/data/repository/latest_sks_user_data_repo.dart
  lib/features/sks_people_live/presentation/widgets/sks_user_data_button.dart
  lib/l10n/app_pl.arb
  lib/shared_api_clients/sks_api_client.dart
  lib/utils/datetime_utils.dart
Labels: enhancement, DEV

#414 Add padding to all elements if there is system padding
  lib/features/home_view/home_view.dart
Labels: bug

#419 Add Align to center error text in landscape mode
  lib/features/offline_messages/widgets/general_offline_message.dart
  lib/widgets/my_error_widget.dart
Labels: bug

#422 Chore/sks update url and adjust dish model
  lib/features/sks-menu/data/models/sks_menu_data.dart
  lib/features/sks-menu/data/models/sks_menu_response.dart
  lib/features/sks-menu/data/repository/sks_menu_repository.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
Labels: chore

#434 fix: correct pop view app bar buttons' titles
  lib/features/about_us_view/about_us_view.dart
  lib/features/department_detail_view/department_detail_view.dart
  lib/features/departments_view/departments_view.dart
  lib/features/guide_detail_view/guide_detail_view.dart
  lib/features/navigation_tab_view/navigation_tab_view.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/features/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
  lib/features/update_dialog/presentation/update_dialog_wrapper.dart
  lib/l10n/app_pl.arb
  lib/widgets/detail_views/detail_view_app_bar.dart
  lib/widgets/detail_views/pop_button.dart
  lib/widgets/search_box_app_bar.dart
Labels: bug

#436 feat: implement review request open store
  lib/features/navigation_tab_view/navigation_tab_view.dart
Labels: enhancement

#428 Feat/add lottie animation
  assets/animations/sks_closed.json
  lib/features/sks-menu/presentation/sks_menu_screen.dart
  lib/l10n/app_pl.arb
  pubspec.yaml
Labels: enhancement

#440 feat: add navigation aware back button
  lib/config/nav_bar_config.dart
  lib/features/about_us_view/about_us_view.dart
  lib/features/department_detail_view/department_detail_view.dart
  lib/features/departments_view/departments_view.dart
  lib/features/guide_detail_view/guide_detail_view.dart
  lib/features/navigation_tab_view/navigation_tab_view.dart
  lib/features/navigator/navigation_controller.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/features/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
  lib/widgets/detail_views/detail_view_app_bar.dart
  lib/widgets/detail_views/pop_button.dart
  lib/widgets/search_box_app_bar.dart
Labels: enhancement

#445 refactor: fix padding
  lib/config/ui_config.dart
  lib/features/navigation_tab_view/widgets/notification_button.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
Labels: bug
