Repository Solvro/mobile-topwr, pull requests merged in 2025-06, with the labels that each got.

#737 feat/add-accesibility-for-dialogs
  lib/features/about_us_view/utils/custom_license_dialog.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/accessibility_dialog.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/red_dialog.dart
  lib/features/navigation_tab_view/widgets/notification_dialog.dart
  lib/features/science_club/science_clubs_view/widgets/science_clubs_info_dialog.dart
  lib/features/settings/widgets/language_settings_dialog.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/widgets/my_alert_dialog.dart
  lib/widgets/zoomable_images.dart
Labels: size/L

#740 fix: my alert dialog font size buttons on normal size font
  lib/widgets/my_alert_dialog.dart
Labels: bug, size/M

#744 feat(home): improve accessibility
  fonts/StrategicClubBadges.ttf
  fonts/StrategucClubBadges.json
  lib/features/academic_calendar/utils/counter_digits.dart
  lib/features/academic_calendar/widgets/countdown_widget/digits_widgets.dart
  lib/features/academic_calendar/widgets/countdown_widget/exam_session_countdown.dart
  lib/features/academic_calendar/widgets/home_screen_greeting.dart
  lib/features/academic_calendar/widgets/incoming_day_changes.dart
  lib/features/home_view/widgets/buildings_section/building_card.dart
  lib/features/home_view/widgets/logo_app_bar.dart
  lib/features/home_view/widgets/nav_actions_section.dart
  lib/features/home_view/widgets/science_clubs_section.dart
  lib/features/science_club/science_clubs_view/widgets/strategic_badge.dart
  lib/features/science_club/science_clubs_view/widgets/strategic_club_badges.icons.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/widgets/subsection_header.dart
  pubspec.yaml
Labels: enhancement, size/L

#749 feat: add accessibility support for update dialog
  lib/features/app_changelog/app_changelog.dart
  lib/features/app_changelog/widgets/app_changelog_header.dart
Labels: enhancement, size/M

#748 feat(departments): improve accessibility for department's list & details screen
  lib/features/departments/department_detail_view/department_detail_view.dart
  lib/features/departments/department_detail_view/widgets/field_of_study_tile.dart
  lib/features/departments/department_detail_view/widgets/science_clubs_section.dart
  lib/features/departments/departments_view/departments_view.dart
  lib/features/departments/departments_view/widgets/department_card.dart
  lib/widgets/wide_tile_card.dart
Labels: size/M

#764 feat(sci-clubs): improve accessibility
  lib/config/ui_config.dart
  lib/features/science_club/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_club/science_clubs_filters/filters_sheet.dart
  lib/features/science_club/science_clubs_filters/widgets/departments_wrap.dart
  lib/features/science_club/science_clubs_filters/widgets/filter_chip.dart
  lib/features/science_club/science_clubs_filters/widgets/filters_fab.dart
  lib/features/science_club/science_clubs_filters/widgets/filters_search.dart
  lib/features/science_club/science_clubs_filters/widgets/tags_wrap.dart
  lib/features/science_club/science_clubs_filters/widgets/types_wrap.dart
  lib/features/science_club/science_clubs_view/science_clubs_view.dart
  lib/features/science_club/science_clubs_view/widgets/science_club_card.dart
  lib/features/science_club/science_clubs_view/widgets/science_clubs_list.dart
  lib/features/science_club/science_clubs_view/widgets/science_clubs_view_loading.dart
  lib/features/science_club/science_clubs_view/widgets/verified_badge.dart
  lib/hooks/use_semantics_service_on_changed_value.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: enhancement, size/L

#765 fix(digital-guide): load external CA certificate
  assets/certs/przewodnik.pwr.edu.pl.pem
  lib/api_base_rest/client/dio_client.dart
  lib/main.dart
  pubspec.yaml
Labels: bug, size/M

#766 fix(parkings): fix parkings tile bug
  lib/features/parkings/parkings_view/widgets/parking_wide_tile_card.dart
Labels: size/S
