Repository Solvro/mobile-topwr, pull requests merged in 2025-05, with the labels that each got.

#706 feat: accessibility for about us screen
  lib/features/about_us_view/utils/custom_license_dialog.dart
  lib/features/about_us_view/widgets/app_version.dart
  lib/features/about_us_view/widgets/contact_section.dart
  lib/features/about_us_view/widgets/team_section.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/utils/html_to_plain_text.dart
  lib/widgets/detail_views/sliver_header_section.dart
  lib/widgets/my_html_widget.dart
Labels: enhancement, size/L

#714 feat(academic-calendar): implement upcoming day changes alert
  lib/api_base/schema.graphql
  lib/config/ui_config.dart
  lib/features/about_us_view/repository/about_us_repository.dart
  lib/features/academic_calendar/model/academic_calendar_extensions.dart
  lib/features/academic_calendar/model/academic_week_exception.dart
  lib/features/academic_calendar/repository/academic_calendar_repo.dart
  lib/features/academic_calendar/repository/getAcademicCalendar.graphql
  lib/features/academic_calendar/utils/localize_academic_day.dart
  lib/features/academic_calendar/widgets/academic_calendar_consumer.dart
  lib/features/academic_calendar/widgets/countdown_widget/exam_session_countdown.dart
  lib/features/academic_calendar/widgets/day_changes_dialog.dart
  lib/features/academic_calendar/widgets/home_screen_greeting.dart
  lib/features/academic_calendar/widgets/incoming_day_changes.dart
  lib/features/departments/department_detail_view/repository/department_details_repository.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/red_dialog.dart
  lib/features/home_view/home_view.dart
  lib/features/planner_advert/repository/planner_advert_repository.dart
  lib/features/planner_advert/widgets/banner_visibility.dart
  lib/features/planner_advert/widgets/planer_ad_badge.dart
  lib/features/planner_advert/widgets/planer_badge_dialog.dart
  lib/features/planner_advert/widgets/planner_advert_widget.dart
  lib/features/science_club/science_club_detail_view/repository/science_club_details_repository.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/utils/datetime_utils.dart
  lib/widgets/my_alert_dialog.dart
  lib/widgets/my_splash_tile.dart
  lib/widgets/technical_message.dart
Labels: size/XL

#715 fix(about-us): restore touch for team members list
  lib/features/about_us_view/widgets/team_section.dart
Labels: size/L

#716 feat(about-us): change loading to shimmer one
  lib/features/about_us_view/widgets/team_section.dart
Labels: size/M

#721 fix: change android push notification icon for firebase
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable/ic_notification.webp
Labels: size/XS

#726 feat(sks-menu): accessibility adjustments
  lib/features/home_view/widgets/nav_actions_section.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_header.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_labels.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_legend.dart
  lib/features/sks/sks_chart/presentation/sks_chart_card.dart
  lib/features/sks/sks_chart/presentation/sks_chart_sheet.dart
  lib/features/sks/sks_menu/presentation/widgets/sks_menu_header.dart
  lib/features/sks/sks_menu/presentation/widgets/sks_menu_tiles.dart
  lib/features/sks/sks_people_live/presentation/widgets/sks_user_data_button.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/widgets/detail_views/detail_view_app_bar.dart
  lib/widgets/detail_views/pop_button.dart
  lib/widgets/text_and_url_widget.dart
Labels: size/XL

#725 feat: accessibility navigation tab view
  lib/features/about_us_view/utils/custom_license_dialog.dart
  lib/features/analytics/show_feedback_tile.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/red_dialog.dart
  lib/features/navigation_tab_view/navigation_tab_view.dart
  lib/features/settings/widgets/language_settings_dialog.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: enhancement, size/M

#722 Feat/rest for student clubs
  lib/features/departments/department_detail_view/presentation/widgets/science_clubs_section.dart
  lib/features/home_view/widgets/science_clubs_section.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/features/science_club/science_club_detail_view/model/science_club_details.dart
  lib/features/science_club/science_club_detail_view/repository/getScienceClubDetails.graphql
  lib/features/science_club/science_club_detail_view/repository/science_club_details_repository.dart
  lib/features/science_club/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_club/science_clubs_filters/filters_controller.dart
  lib/features/science_club/science_clubs_filters/filters_search_controller.dart
  lib/features/science_club/science_clubs_filters/filters_sheet.dart
  lib/features/science_club/science_clubs_filters/model/tags.dart
  lib/features/science_club/science_clubs_filters/repository/getTags.graphql
  lib/features/science_club/science_clubs_filters/repository/tags_repository.dart
  lib/features/science_club/science_clubs_filters/widgets/tags_wrap.dart
  lib/features/science_club/science_clubs_view/controllers/science_clubs_view_controller.dart
  lib/features/science_club/science_clubs_view/model/science_clubs.dart
  lib/features/science_club/science_clubs_view/repository/getScienceClubs.graphql
  lib/features/science_club/science_clubs_view/repository/science_clubs_repository.dart
  lib/features/science_club/science_clubs_view/science_clubs_view.dart
  lib/features/science_club/science_clubs_view/widgets/science_club_card.dart
  lib/features/science_club/science_clubs_view/widgets/science_clubs_list.dart
Labels: size/L

#732 feat: replace GraphQL with REST in buildings
  lib/features/buildings_view/building_tile.dart
  lib/features/buildings_view/buildings_view.dart
  lib/features/buildings_view/controllers.dart
  lib/features/buildings_view/model/building_data.dart
  lib/features/buildings_view/model/building_model.dart
  lib/features/buildings_view/repository/buildings_repository.dart
  lib/features/buildings_view/repository/getBuildings.graphql
  lib/features/buildings_view/utils/building_codes_utils.dart
  lib/features/buildings_view/utils/utils.dart
  lib/features/digital_guide/data/repository/digital_guide_repository.dart
  lib/features/digital_guide_objects/data/repositories/digital_guide_object_repository.dart
  lib/features/home_view/widgets/buildings_section/buildings_section.dart
Labels: enhancement, size/L

#735 feat(buildings): add accessibility for building screen list
  lib/features/bottom_scroll_sheet/bottom_scroll_sheet.dart
  lib/features/bottom_scroll_sheet/navigate_button.dart
  lib/features/buildings_view/building_tile.dart
  lib/features/map_view/widgets/map_widget.dart
  lib/features/my_location_button/presentation/my_loc_button.dart
  lib/features/offline_messages/widgets/general_offline_message.dart
  lib/features/science_club/science_clubs_view/widgets/science_clubs_info_dialog.dart
  lib/features/science_club/science_clubs_view/widgets/strategic_badge.dart
  lib/features/science_club/science_clubs_view/widgets/verified_badge.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_header.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_labels.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_legend.dart
  lib/features/sks/sks_chart/presentation/sks_chart_sheet.dart
  lib/features/sks/sks_menu/presentation/widgets/sks_menu_tiles.dart
  lib/hooks/use_semantics_service_on_changed_value.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/utils/context_extensions.dart
  lib/widgets/dual_text_max_lines.dart
  lib/widgets/search_box.dart
  lib/widgets/search_box_app_bar.dart
  lib/widgets/text_and_url_widget.dart
  lib/widgets/wide_tile_card.dart
Labels: enhancement, size/L

#727 Feat/replace academic calendar with restapi
  android/settings.gradle
  lib/features/academic_calendar/model/academic_calendar.dart
  lib/features/academic_calendar/model/academic_calendar_extensions.dart
  lib/features/academic_calendar/model/academic_week_exception.dart
  lib/features/academic_calendar/model/day_swap.dart
  lib/features/academic_calendar/model/day_swap_model.dart
  lib/features/academic_calendar/repository/academic_calendar_repo.dart
  lib/features/academic_calendar/repository/getAcademicCalendar.graphql
  lib/features/academic_calendar/utils/counter_digits.dart
  lib/features/academic_calendar/utils/localize_counter_message.dart
  lib/features/academic_calendar/widgets/academic_calendar_consumer.dart
  lib/features/academic_calendar/widgets/countdown_widget/digits_widgets.dart
  lib/features/academic_calendar/widgets/countdown_widget/exam_session_countdown.dart
  lib/features/academic_calendar/widgets/home_screen_greeting.dart
  pubspec.yaml
Labels: size/L

#733 feat: add accessibility to parkings view
  lib/features/buildings_view/buildings_view.dart
  lib/features/map_view/map_view.dart
  lib/features/map_view/widgets/map_widget.dart
  lib/features/my_location_button/presentation/my_loc_button.dart
  lib/features/parkings/parking_chart/chart_elements/labels_bottom.dart
  lib/features/parkings/parking_chart/chart_elements/labels_left.dart
  lib/features/parkings/parking_chart/parking_chart.dart
  lib/features/parkings/parking_chart/widgets/chart_widget.dart
  lib/features/parkings/parking_chart/widgets/reversed_label.dart
  lib/features/parkings/parkings_view/parkings_view.dart
  lib/features/parkings/parkings_view/widgets/parking_favourite.dart
  lib/features/parkings/parkings_view/widgets/parking_wide_tile_card.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/widgets/search_box.dart
  lib/widgets/search_box_app_bar.dart
Labels: size/L

#736 feat: accessibility for day swap dialog and banner
  lib/features/academic_calendar/widgets/incoming_day_changes.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: enhancement, size/M
