Repository Solvro/mobile-topwr, pull requests merged in 2025-09, with the labels that each got.

#833 feat(multilayer-map): replace topwr logos with specific icons
  android/app/build.gradle
  assets/svg/map_placeholders/aed_icon.svg
  assets/svg/map_placeholders/building_icon.svg
  assets/svg/map_placeholders/library_icon.svg
  assets/svg/map_placeholders/pink_box.png
  assets/svg/map_placeholders/pink_box_icon.svg
  assets/svg/map_placeholders/polinka_icon.svg
  assets/svg/map_placeholders/shower_icon.svg
  lib/features/multilayer_map/data/model/building.dart
  lib/features/multilayer_map/presentation/widgets/aed_tile.dart
  lib/features/multilayer_map/presentation/widgets/bicycle_shower_tile.dart
  lib/features/multilayer_map/presentation/widgets/building_tile.dart
  lib/features/multilayer_map/presentation/widgets/library_tile.dart
  lib/features/multilayer_map/presentation/widgets/multilayer_marker.dart
  lib/features/multilayer_map/presentation/widgets/pink_box_tile.dart
  lib/widgets/wide_tile_card.dart
  pubspec.yaml
Labels: size/L

#834 feat(multilayer-map): new toolbar and map layer picker
  lib/features/analytics/data/umami_events.dart
  lib/features/bottom_scroll_sheet/map_data_sheet_list.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/red_dialog.dart
  lib/features/map_layer_picker/business/layers_enabled_service.dart
  lib/features/map_layer_picker/business/multilayer_source_service.dart
  lib/features/map_layer_picker/data/layer_options.dart
  lib/features/map_layer_picker/data/local_layers_repository.dart
  lib/features/map_layer_picker/presentation/labels.dart
  lib/features/map_layer_picker/presentation/layer_marker_icon.dart
  lib/features/map_layer_picker/presentation/layer_options_dialog.dart
  lib/features/map_layer_picker/presentation/layers_toolbar_button.dart
  lib/features/map_layer_picker/presentation/map_layer_checkbox.dart
  lib/features/map_view/controllers/active_map_marker_cntrl.dart
  lib/features/map_view/widgets/map_widget.dart
  lib/features/map_view/widgets/toolbar.dart
  lib/features/multilayer_map/business/multilayer_source_service.dart
  lib/features/multilayer_map/presentation/controllers.dart
  lib/features/multilayer_map/presentation/widgets/aed_tile.dart
  lib/features/multilayer_map/presentation/widgets/bicycle_shower_tile.dart
  lib/features/multilayer_map/presentation/widgets/building_tile.dart
  lib/features/multilayer_map/presentation/widgets/library_tile.dart
  lib/features/multilayer_map/presentation/widgets/pink_box_tile.dart
  lib/features/my_loc_button/data/location_permission_status_provider.dart
  lib/features/my_loc_button/presentation/branches_button.dart
  lib/features/my_loc_button/presentation/is_following_controller.dart
  lib/features/my_loc_button/presentation/my_loc_button.dart
  lib/features/my_loc_button/presentation/my_loc_layer.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: size/XL

#835 fix(multilayer-map): map virtualization
  lib/features/bottom_scroll_sheet/multilayer_map_single_entity_list.dart
Labels: size/S

#838 feat(calendar): add event calendar view
  commitlint.yaml
  lib/features/analytics/data/umami_events.dart
  lib/features/calendar/bussiness/get_events_per_days_use_case.dart
  lib/features/calendar/bussiness/models.dart
  lib/features/calendar/data/model/calendar_data.dart
  lib/features/calendar/data/repository/calendar_repository.dart
  lib/features/calendar/presentation/calendar_day_section.dart
  lib/features/calendar/presentation/calendar_search_controller.dart
  lib/features/calendar/presentation/calendar_tile.dart
  lib/features/calendar/presentation/calendar_view.dart
  lib/features/calendar/utils/calendar_view_extension.dart
  lib/features/home_view/widgets/nav_actions_section.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/theme/app_text_theme.dart
  lib/theme/typography.dart
  lib/widgets/my_alert_dialog.dart
Labels: size/XL
