Repository Solvro/mobile-topwr, pull requests merged in 2025-02, with the labels that each got.

#571 /feat(digital-guide): create loading screen #483
  .fvm/flutter_sdk
  .fvm/fvm_config.json
  .fvmrc
  lib/features/buildings_view/building_tile.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_loading_view.dart
Labels: enhancement

#572 bug: Sks menu button fix
  lib/features/sks_menu/presentation/sks_menu_screen.dart
Labels: bug

#538 Digital Guide structure tab
  l10n.yaml
  lib/config/nav_bar_config.dart
  lib/config/ui_config.dart
  lib/features/digital_guide/data/models/level.dart
  lib/features/digital_guide/data/models/level_with_regions.dart
  lib/features/digital_guide/data/models/region.dart
  lib/features/digital_guide/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide/tabs/adapted_toilets/data/repository/adapted_toilets_repository.dart
  lib/features/digital_guide/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
  lib/features/digital_guide/tabs/dressing_room/data/repository/dressing_rooms_repository.dart
  lib/features/digital_guide/tabs/lifts/data/repository/lifts_repository.dart
  lib/features/digital_guide/tabs/lifts/domain/digital_guide_lifts_use_cases.dart
  lib/features/digital_guide/tabs/lodge/data/repository/lodges_repository.dart
  lib/features/digital_guide/tabs/rooms/data/repository/rooms_repository.dart
  lib/features/digital_guide/tabs/rooms/domain/digital_guide_rooms_use_cases.dart
  lib/features/digital_guide/tabs/rooms/presentation/digital_guide_room_detail_view.dart
  lib/features/digital_guide/tabs/structure/data/models/corridor.dart
  lib/features/digital_guide/tabs/structure/data/models/information_point.dart
  lib/features/digital_guide/tabs/structure/data/models/parking.dart
  lib/features/digital_guide/tabs/structure/data/models/ramp.dart
  lib/features/digital_guide/tabs/structure/data/models/stairs.dart
  lib/features/digital_guide/tabs/structure/data/models/stairway.dart
  lib/features/digital_guide/tabs/structure/data/models/toilet.dart
  lib/features/digital_guide/tabs/structure/data/repository/corridors_repository.dart
  lib/features/digital_guide/tabs/structure/data/repository/information_points_repository.dart
  lib/features/digital_guide/tabs/structure/data/repository/ramps_repository.dart
  lib/features/digital_guide/tabs/structure/data/repository/region_parkings_repository.dart
  lib/features/digital_guide/tabs/structure/data/repository/stairs_repository.dart
  lib/features/digital_guide/tabs/structure/data/repository/stairways_repository.dart
  lib/features/digital_guide/tabs/structure/data/repository/toilets_repository.dart
  lib/features/digital_guide/tabs/structure/domain/digital_guide_region_use_cases.dart
  lib/features/digital_guide/tabs/structure/presentation/structure_expansion_tile_content.dart
  lib/features/digital_guide/tabs/structure/presentation/views/corridor_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/level_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_data_sliver_list.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_data_sliver_list_item.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_view.dart
  lib/features/digital_guide/tabs/surrounding/data/models/surrounding_response.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#589 feat(sks-chart): shimmer loading (#587)
  lib/features/sks/sks_chart/presentation/sks_chart_sheet.dart
Labels: enhancement

#584 528 feat digital guide screens for academics and polinka
  lib/features/digital_guide/presentation/widgets/accessibility_information_card.dart
  lib/features/digital_guide/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide/tabs/surrounding/presentation/surroundings_expansion_tile_content.dart
  lib/features/digital_guide/tabs/surrounding/presentation/widgets/accessibility_information_cards_list.dart
  lib/features/digital_guide_objects/data/models/digital_guide_object_model.dart
  lib/features/digital_guide_objects/data/models/digital_guide_object_tab_model.dart
  lib/features/digital_guide_objects/data/repositories/digital_guide_object_repository.dart
  lib/features/digital_guide_objects/data/repositories/digital_guide_tabs_repository.dart
  lib/features/digital_guide_objects/presentation/digital_g_objects_amenietes_tab_tile_content.dart
  lib/features/digital_guide_objects/presentation/digital_g_objects_featers_list.dart
  lib/features/digital_guide_objects/presentation/digital_guide_object_view.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/widgets/detail_views/contact_section.dart
Labels: enhancement

#591 Feat/add accessibility profile widget
  lib/features/digital_guide/business/accessibility_comments_manager.dart
  lib/features/digital_guide/presentation/widgets/accessibility_profile_card.dart
  lib/features/digital_guide/tabs/accessibility_dialog/business/top_level_modes.dart
  lib/features/digital_guide/tabs/accessibility_dialog/data/active_accessibility_modes_repository.dart
  lib/features/digital_guide/tabs/accessibility_dialog/data/modes.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/labels.dart
  lib/features/digital_guide/tabs/entraces/presentation/entraces_detail_view.dart
  lib/features/digital_guide/tabs/lifts/business/lifts_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/lifts/data/models/digital_guide_lift.dart
  lib/features/digital_guide/tabs/lifts/presentation/digital_guide_lift_detail_view.dart
  lib/features/digital_guide/tabs/rooms/platforms/presentation/room_platforms_content.dart
  lib/features/digital_guide/tabs/rooms/stairs/presentation/room_stairs_content.dart
  lib/features/digital_guide/tabs/surrounding/business/surroundings_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/surrounding/presentation/surroundings_expansion_tile_content.dart
  lib/features/digital_guide/tabs/surrounding/utils/surrounding_response_operations.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#600 Toilets in structure tab
  lib/features/digital_guide/tabs/structure/data/bussiness/toilets_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/data/models/toilet.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/toilets_view.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#601 Feat/railings in structure tab
  lib/features/digital_guide/tabs/structure/data/bussiness/railings_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/data/models/railing.dart
  lib/features/digital_guide/tabs/structure/data/models/stairs.dart
  lib/features/digital_guide/tabs/structure/data/repository/railings_repository.dart
  lib/features/digital_guide/tabs/structure/presentation/views/railings_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairs_view.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#602 fix(digital-guide): borders bug in new tabs
  lib/features/digital_guide/tabs/adapted_toilets/presentation/adapted_toilets_expansion_tile_content.dart
  lib/features/digital_guide/tabs/entraces/presentation/entraces_expansion_tile_content.dart
  lib/features/digital_guide/tabs/structure/presentation/structure_expansion_tile_content.dart
Labels: bug

#603 feat: add accessibility card for transport
  lib/features/digital_guide/tabs/transportation/business/non_public_transportation_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/transportation/business/public_transportation_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/transportation/data/models/digital_guide_transportation.dart
  lib/features/digital_guide/tabs/transportation/presentation/transportation_detail_view.dart
  lib/l10n/app_pl.arb
Labels: enhancement, help wanted

#614 /feat(digital-guide): add "Stairway" section to structure tab
  lib/features/digital_guide/tabs/structure/data/bussiness/stairway_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/data/models/stairs.dart
  lib/features/digital_guide/tabs/structure/data/models/stairway.dart
  lib/features/digital_guide/tabs/structure/data/repository/stairs_repository.dart
  lib/features/digital_guide/tabs/structure/domain/digital_guide_region_use_cases.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairs_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairway_view.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#617 Feat/accessibility dressing rooms
  lib/features/digital_guide/tabs/dressing_room/data/models/digital_guide_dressing_room.dart
  lib/features/digital_guide/tabs/dressing_room/domain/dressing_room_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/dressing_room/presentation/digital_guide_dressing_rooms_expansion_tile.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#618 Feat(digital-guide): information points
  lib/features/digital_guide/data/models/optional_tiles_data.dart
  lib/features/digital_guide/data/repository/digital_guide_repository.dart
  lib/features/digital_guide/data/repository/optional_tiles_data_repository.dart
  lib/features/digital_guide/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide/tabs/information_points/models/digital_guide_information_points.dart
  lib/features/digital_guide/tabs/information_points/models/information_point_accessibility_manager.dart
  lib/features/digital_guide/tabs/information_points/repository/information_point_repository.dart
  lib/features/digital_guide/tabs/information_points/widgets/information_point_widget.dart
  lib/l10n/app_pl.arb
  lib/utils/type_converter.dart
Labels: enhancement
