Repository Solvro/mobile-topwr, pull requests merged in 2025-01, with the labels that each got.

#513 Feat/digital guide add surroundings
  assets/svg/digital_guide/accessibility_alerts/blind_profile.svg
  assets/svg/digital_guide/accessibility_alerts/cognitive_difficulties.svg
  assets/svg/digital_guide/accessibility_alerts/hearing_dysfunction.svg
  assets/svg/digital_guide/accessibility_alerts/movement_dysfunction.svg
  assets/svg/digital_guide/accessibility_alerts/sensory_sensitivity.svg
  assets/svg/digital_guide/accessibility_alerts/visually_impaired.svg
  lib/config/ui_config.dart
  lib/features/digital_guide_view/data/models/digital_guide_response.dart
  lib/features/digital_guide_view/presentation/widgets/accessibility_information_card.dart
  lib/features/digital_guide_view/presentation/widgets/accessibility_profile_card.dart
  lib/features/digital_guide_view/presentation/widgets/bullet_list.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_photo_row.dart
  lib/features/digital_guide_view/tabs/surrounding/data/models/surrounding_response.dart
  lib/features/digital_guide_view/tabs/surrounding/data/models/surrounding_response_extended.dart
  lib/features/digital_guide_view/tabs/surrounding/data/repository/surrounding_repository.dart
  lib/features/digital_guide_view/tabs/surrounding/presentation/surroundings_expansion_tile_content.dart
  lib/features/digital_guide_view/tabs/surrounding/presentation/widgets/accessibility_information_cards_list.dart
  lib/features/digital_guide_view/tabs/surrounding/utils/surrounding_response_operations.dart
  lib/features/home_view/widgets/nav_actions_section.dart
  lib/l10n/app_pl.arb
  pubspec.yaml
Labels: enhancement

#514 Digital guide API foundation and adapted toilets
  lib/config/nav_bar_config.dart
  lib/features/digital_guide_view/data/models/digital_guide_response.dart
  lib/features/digital_guide_view/data/models/digital_guide_response_extended.dart
  lib/features/digital_guide_view/data/repository/digital_guide_repository.dart
  lib/features/digital_guide_view/data/repository/levels_repository.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_nav_link.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/data/models/adapted_toilet.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/data/models/adapted_toilet_not_full.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/data/repository/adapted_toilets_repository.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilets_expansion_tile_content.dart
  lib/features/home_view/widgets/science_clubs_section.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
  lib/widgets/my_point_widget.dart
Labels: enhancement

#520 fix(digital-guide): ui changes to amnesties and surroundings tiles
  lib/config/ui_config.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/digital_guide_view/presentation/widgets/accessibility_information_card.dart
  lib/features/digital_guide_view/presentation/widgets/report_change_button.dart
  lib/features/digital_guide_view/tabs/amenities/presentation/amenities_expansion_tile_content.dart
  lib/features/digital_guide_view/tabs/surrounding/presentation/surroundings_expansion_tile_content.dart
  lib/widgets/detail_views/contact_section.dart
Labels: enhancement

#488 #449 feat/ add fullscreen mode for photos in detail views
  lib/api_base/directus_assets_url.dart
  lib/config/ui_config.dart
  lib/features/about_us_view/widgets/team_section.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_image.dart
  lib/features/guide_detail_view/guide_detail_view.dart
  lib/features/home_view/widgets/science_clubs_section.dart
  lib/widgets/detail_views/sliver_header_section.dart
  lib/widgets/detail_views/sliver_logo.dart
  lib/widgets/optimized_directus_image.dart
  lib/widgets/zoomable_optimized_directus_image.dart
Labels: enhancement

#524 Refactor/digital guide data layer and add persistent caching
  analysis_options.yaml
  lib/api_base_rest/cache/cache.dart
  lib/api_base_rest/client/dio_client.dart
  lib/api_base_rest/client/offline_error.dart
  lib/features/digital_guide_view/data/api/digital_guide_get_and_cache.dart
  lib/features/digital_guide_view/data/models/digital_guide_response.dart
  lib/features/digital_guide_view/data/models/digital_guide_response_extended.dart
  lib/features/digital_guide_view/data/models/level.dart
  lib/features/digital_guide_view/data/models/level_with_regions.dart
  lib/features/digital_guide_view/data/models/region.dart
  lib/features/digital_guide_view/data/repository/digital_guide_repository.dart
  lib/features/digital_guide_view/data/repository/image_repository.dart
  lib/features/digital_guide_view/data/repository/levels_repository.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_image.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_photo_row.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/business/adapted_toilets_use_cases.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/data/models/adapted_toilet.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/data/repository/adapted_toilets_repository.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilet_level.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilets_expansion_tile_content.dart
  lib/features/digital_guide_view/tabs/amenities/presentation/amenities_expansion_tile_content.dart
  lib/features/digital_guide_view/tabs/entraces/data/repository/entraces_repository.dart
  lib/features/digital_guide_view/tabs/evacuation/data/models/digital_guide_evacuation.dart
  lib/features/digital_guide_view/tabs/evacuation/data/repository/evacuation_repository.dart
  lib/features/digital_guide_view/tabs/evacuation/entrances_list.dart
  lib/features/digital_guide_view/tabs/evacuation/evacuation_widget.dart
  lib/features/digital_guide_view/tabs/surrounding/data/models/surrounding_response.dart
  lib/features/digital_guide_view/tabs/surrounding/data/models/surrounding_response_extended.dart
  lib/features/digital_guide_view/tabs/surrounding/data/repository/surrounding_repository.dart
  lib/features/digital_guide_view/tabs/surrounding/presentation/surroundings_expansion_tile_content.dart
  lib/features/digital_guide_view/tabs/surrounding/presentation/widgets/accessibility_information_cards_list.dart
  lib/features/digital_guide_view/tabs/surrounding/utils/surrounding_response_operations.dart
  lib/features/parkings_view/models/parking.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#531 Feat/digital guide rooms
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/readme.md
  lib/features/digital_guide_view/tabs/rooms/data/models/digital_guide_room.dart
  lib/features/digital_guide_view/tabs/rooms/data/repository/rooms_repository.dart
  lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_room_detail_view.dart
  lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_rooms_expansion_tile_content.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#533 Feat/connect digital guide
  lib/api_base/schema.graphql
  lib/features/buildings_view/building_tile.dart
  lib/features/buildings_view/model/building_model.dart
  lib/features/buildings_view/repository/getBuildings.graphql
  lib/features/digital_guide_view/data/repository/digital_guide_repository.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/home_view/widgets/nav_actions_section.dart
  lib/features/navigator/utils/navigation_commands.dart
Labels: enhancement

#534 feat(digital-guide): add support for levels
  lib/features/digital_guide_view/data/models/region.dart
  lib/features/digital_guide_view/tabs/rooms/data/repository/rooms_repository.dart
  lib/features/digital_guide_view/tabs/rooms/domain/digital_guide_rooms_use_cases.dart
  lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_room_level.dart
  lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_rooms_expansion_tile_content.dart
Labels: enhancement

#532 Feat(digital guide)/add micronavigation info
  README.md
  example.env
  lib/config/env.dart
  lib/config/ui_config.dart
  lib/features/digital_guide_view/data/models/digital_guide_response.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/readme.md
  lib/features/digital_guide_view/tabs/micronavigation/data/models/micronavigation_response.dart
  lib/features/digital_guide_view/tabs/micronavigation/data/repository/micronavigation_repository.dart
  lib/features/digital_guide_view/tabs/micronavigation/presentation/micronavigation_detail_view.dart
  lib/features/digital_guide_view/tabs/micronavigation/presentation/micronavigation_expansion_tile_content.dart
  lib/features/digital_guide_view/tabs/micronavigation/presentation/widgets/my_audio_player.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
  lib/utils/duration_utils.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#537 feat(digital-guide): add accessibility modes dialog
  lib/config/ui_config.dart
  lib/features/digital_guide_view/presentation/widgets/accessibility_button.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/business/accessibility_mode_service.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/business/top_level_modes.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/data/accessibility_mode_repository.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/data/modes.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/accessibility_dialog.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/checkboxes_list.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/labels.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/mode_checkbox.dart
  lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/red_dialog.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#539 fix: even horizontal allignment
  lib/features/about_us_view/about_us_view.dart
  lib/features/app_changelog/app_changelog.dart
  lib/features/app_changelog/widgets/app_changelog_list.dart
  lib/features/bottom_scroll_sheet/sheet_layout_scheme.dart
  lib/features/department_detail_view/department_detail_view.dart
  lib/features/departments_view/departments_view.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
  lib/features/digital_guide_view/tabs/micronavigation/presentation/micronavigation_detail_view.dart
  lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_room_detail_view.dart
  lib/features/home_view/home_view.dart
  lib/features/home_view/widgets/logo_app_bar.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/root_view.dart
  lib/features/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_club_detail_view/widgets/about_us_section_loading.dart
  lib/features/science_clubs_filters/filters_sheet.dart
  lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
  lib/features/sks_chart/presentation/sks_chart_sheet.dart
  lib/main.dart
  lib/widgets/detail_views/detail_view_app_bar.dart
  lib/widgets/horizontal_symmetric_safe_area.dart
  lib/widgets/search_box_app_bar.dart
Labels: bug

#545 Add lodge to digital guide
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/readme.md
  lib/features/digital_guide_view/tabs/lodge/data/models/digital_guide_lodge.dart
  lib/features/digital_guide_view/tabs/lodge/data/repository/lodges_repository.dart
  lib/features/digital_guide_view/tabs/lodge/presentation/digital_guide_lodge_expansion_tile_content.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#546 Fix adjust sks menu animation/icon in horizontal mode
  lib/features/sks-menu/presentation/sks_menu_screen.dart
Labels: bug

#548 Add lifts to digital guide
  lib/features/digital_guide_view/data/models/region.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/readme.md
  lib/features/digital_guide_view/tabs/lifts/data/models/digital_guide_lift.dart
  lib/features/digital_guide_view/tabs/lifts/data/repository/lifts_repository.dart
  lib/features/digital_guide_view/tabs/lifts/domain/digital_guide_lifts_use_cases.dart
  lib/features/digital_guide_view/tabs/lifts/presentation/digital_guide_lift_detail_view.dart
  lib/features/digital_guide_view/tabs/lifts/presentation/digital_guide_lift_level.dart
  lib/features/digital_guide_view/tabs/lifts/presentation/digital_guide_lifts_expansion_tile_content.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#557 Add planner advert
  lib/api_base/schema.graphql
  lib/config/ttl_config.dart
  lib/features/academic_calendar/widgets/academic_calendar_consumer.dart
  lib/features/home_view/home_view.dart
  lib/features/offline_messages/messages_config.dart
  lib/features/planner_advert/repository/getPlannerAdvertContent.graphql
  lib/features/planner_advert/repository/planner_advert_repository.dart
  lib/features/planner_advert/widgets/planner_advert_widget.dart
  lib/features/sks-menu/presentation/sks_menu_screen.dart
  lib/l10n/app_pl.arb
  lib/widgets/loading_widgets/simple_previews/horizontal_rectangular_section_loading.dart
  lib/widgets/technical_message.dart
Labels: enhancement

#521 Feat/add map with building's localization
  lib/features/digital_guide_view/data/models/digital_guide_response.dart
  lib/features/digital_guide_view/presentation/digital_guide_view.dart
  lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide_view/readme.md
  lib/features/digital_guide_view/tabs/localization/presentation/localization_expansion_tile_content.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/l10n/app_pl.arb
Labels: enhancement

#562 Tests for hex colors
  .github/workflows/lint_and_format.yml
  lib/theme/colors.dart
  lib/theme/hex_color.dart
  pubspec.yaml
  test/hex_color_converters_test.dart
  test/widget_test.dart
Labels: chore

#563 Fix/parkings hotfix
  example.env
  lib/api_base/schema.graphql
  lib/config/env.dart
  lib/features/parking_chart/repository/chart_repository.dart
  lib/features/parkings_view/models/parking.dart
  lib/features/parkings_view/pick_correct_api_service/getUseParkingApiWrapper.graphql
  lib/features/parkings_view/repository/parkings_repository.dart
  lib/features/planner_advert/repository/getPlannerAdvertContent.graphql
  lib/features/planner_advert/widgets/planner_advert_widget.dart
  lib/widgets/technical_message.dart
Labels: bug
