Repository Solvro/mobile-topwr, pull requests merged in 2025-03, with the labels that each got.

#599 Add time constant shimmer effect every time you switch team section
  lib/features/about_us_view/widgets/team_section.dart
Labels: enhancement

#625 feat: integrate first solvro config
  .github/dependabot.yaml
  .github/workflows/commit_lint_ci.yaml
  .github/workflows/flutter_ci.yaml
  .github/workflows/pr_title_ci.yaml
  .husky/commit-msg
  .husky/pre-commit
  analysis_options.yaml
  commitlint.yaml
  lib/api_base/query_adapter.dart
  lib/api_base_rest/cache/cache.dart
  lib/features/academic_calendar/model/academic_day.dart
  lib/features/app_changelog/show_changelog.dart
  lib/features/digital_guide/data/models/digital_guide_response.dart
  lib/features/digital_guide/data/models/level.dart
  lib/features/digital_guide/data/models/optional_tiles_data.dart
  lib/features/digital_guide/data/models/region.dart
  lib/features/digital_guide/presentation/widgets/digital_guide_photo_row.dart
  lib/features/digital_guide/tabs/adapted_toilets/data/models/adapted_toilet.dart
  lib/features/digital_guide/tabs/doors/data/model/door.dart
  lib/features/digital_guide/tabs/dressing_room/data/models/digital_guide_dressing_room.dart
  lib/features/digital_guide/tabs/entraces/data/models/digital_guide_entrace.dart
  lib/features/digital_guide/tabs/information_points/models/digital_guide_information_points.dart
  lib/features/digital_guide/tabs/lifts/data/models/digital_guide_lift.dart
  lib/features/digital_guide/tabs/lodge/data/models/digital_guide_lodge.dart
  lib/features/digital_guide/tabs/micronavigation/data/models/micronavigation_response.dart
  lib/features/digital_guide/tabs/rooms/data/models/digital_guide_room.dart
  lib/features/digital_guide/tabs/rooms/platforms/models/room_platforms_response.dart
  lib/features/digital_guide/tabs/rooms/stairs/models/room_stairs_response.dart
  lib/features/digital_guide/tabs/structure/data/models/corridor.dart
  lib/features/digital_guide/tabs/structure/data/models/information_point.dart
  lib/features/digital_guide/tabs/structure/data/models/parking.dart
  lib/features/digital_guide/tabs/structure/data/models/railing.dart
  lib/features/digital_guide/tabs/structure/data/models/ramp.dart
  lib/features/digital_guide/tabs/structure/data/models/stairs.dart
  lib/features/digital_guide/tabs/structure/data/models/stairway.dart
  lib/features/digital_guide/tabs/structure/data/models/toilet.dart
  lib/features/digital_guide/tabs/surrounding/data/models/surrounding_response.dart
  lib/features/digital_guide/tabs/transportation/data/models/digital_guide_transportation.dart
  lib/features/digital_guide_objects/data/models/digital_guide_object_model.dart
  lib/features/digital_guide_objects/data/models/digital_guide_object_tab_model.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/navigation_controller.dart
  lib/features/parkings/parking_chart/models/raw_chart_data.dart
  lib/features/parkings/parking_chart/repository/chart_repository.dart
  lib/features/parkings/parkings_view/api_client/iparking_commands.dart
  lib/features/parkings/parkings_view/models/parking.dart
  lib/features/sks/sks_chart/data/models/sks_chart_data.dart
  lib/features/sks/sks_chart/data/repository/sks_chart_repository.dart
  lib/features/sks/sks_menu/data/models/sks_menu_data.dart
  lib/features/sks/sks_menu/data/models/sks_menu_response.dart
  lib/features/sks/sks_menu/data/models/sks_opening_hours.dart
  lib/features/sks/sks_people_live/data/models/sks_user_data.dart
  lib/features/sks/sks_people_live/data/repository/latest_sks_user_data_repo.dart
  lib/features/splash_screen/splash_screen_controller.dart
  lib/widgets/zoomable_images.dart
  pubspec.yaml
Labels: enhancement

#627 feat: add some bots wip
  .github/weekly-digest.yaml
  .github/workflows/commit_lint_ci.yaml
  .husky/_/husky.sh
Labels: size/M

#628 fix: use `flutter_map_location_marker` from github - temporarly
  pubspec.yaml
Labels: bug, size/XS

#621 feat: Digital guide corridors accessibility
  .husky/_/husky.sh
  lib/features/digital_guide/tabs/structure/business/corridors_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/data/models/corridor.dart
  lib/features/digital_guide/tabs/structure/presentation/views/corridor_view.dart
  lib/l10n/app_pl.arb
  pubspec.yaml
Labels: size/L

#629 fix: add accessibility button to bar when missing + corridor types in presentation layer
  lib/features/digital_guide/tabs/doors/presentation/door_view.dart
  lib/features/digital_guide/tabs/structure/data/models/corridor.dart
  lib/features/digital_guide/tabs/structure/presentation/views/corridor_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/level_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/railings_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/ramps_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairs_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairway_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/toilets_view.dart
  lib/features/navigator/app_router.dart
  lib/l10n/app_pl.arb
Labels: size/L

#633 refactor: move accesibility managers to business layer in structure tab
  lib/features/digital_guide/tabs/structure/business/railings_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/ramps_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/stairs_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/stairway_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/toilets_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/presentation/views/railings_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/ramps_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairs_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairway_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/toilets_view.dart
Labels: size/S

#631 feat: lodge accessibility
  lib/features/digital_guide/tabs/lodge/business/lodge_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/lodge/data/models/digital_guide_lodge.dart
  lib/features/digital_guide/tabs/lodge/presentation/digital_guide_lodge_expansion_tile_content.dart
  lib/l10n/app_pl.arb
Labels: size/M

#632 fix: parking chart hours overlap
  lib/features/parkings/parking_chart/chart_elements/labels_bottom.dart
  lib/utils/angles.dart
Labels: size/S

#634 fix: fill holes in the navigation of digital guide
  lib/config/nav_bar_config.dart
  lib/features/digital_guide/tabs/adapted_toilets/presentation/adapted_toilet_level.dart
  lib/features/digital_guide/tabs/entraces/presentation/entraces_detail_view.dart
  lib/features/digital_guide/tabs/evacuation/entrances_list.dart
  lib/features/digital_guide/tabs/rooms/presentation/digital_guide_room_detail_view.dart
  lib/features/navigator/app_router.dart
Labels: size/M

#637 fix: change externalId field in digital guide response to nullable
  lib/features/digital_guide/data/models/digital_guide_response.dart
  lib/features/digital_guide/presentation/widgets/digital_guide_features_section.dart
  lib/features/digital_guide/tabs/micronavigation/presentation/micronavigation_expansion_tile_content.dart
  lib/l10n/app_pl.arb
Labels: size/S

#636 feat: add accessibility comments to adapted toilets
  lib/features/digital_guide/tabs/adapted_toilets/business/adapted_toilet_accessibility_comments_menager.dart
  lib/features/digital_guide/tabs/adapted_toilets/data/models/adapted_toilet.dart
  lib/features/digital_guide/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
  lib/l10n/app_pl.arb
Labels: size/L

#638 feat: acc manager for doors
  lib/features/digital_guide/tabs/doors/data/model/door.dart
  lib/features/digital_guide/tabs/doors/domain/doors_accessibility_manager.dart
  lib/features/digital_guide/tabs/doors/presentation/door_view.dart
  lib/l10n/app_pl.arb
Labels: size/L

#644 feat: add date to the offline banner
  lib/features/sks/sks_menu/presentation/sks_menu_screen.dart
  lib/l10n/app_pl.arb
Labels: enhancement, size/XS

#635 feat: add accessibility for entrances
  lib/features/digital_guide/tabs/entraces/bussiness/entraces_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/entraces/data/models/digital_guide_entrace.dart
  lib/features/digital_guide/tabs/entraces/presentation/digital_guide_entrance_widget.dart
  lib/features/digital_guide/tabs/entraces/presentation/entraces_detail_view.dart
  lib/features/digital_guide/tabs/evacuation/entrances_list.dart
  lib/l10n/app_pl.arb
Labels: enhancement, size/L

#647 feat: add hour label and enable dots
  lib/config/ui_config.dart
  lib/features/parkings/parking_chart/chart_elements/chart_line.dart
  lib/features/parkings/parking_chart/chart_elements/labels_bottom.dart
  lib/features/parkings/parking_chart/chart_elements/labels_left.dart
  lib/features/parkings/parking_chart/utils/chart_utils.dart
  lib/features/parkings/parking_chart/widgets/chart_widget.dart
  pubspec.yaml
Labels: size/S

#653 feat: setup open ai translations
  .env
  README.md
  example.env
  lib/config/env.dart
  lib/features/parkings/parking_chart/repository/chart_repository.dart
  lib/features/parkings/parkings_view/repository/parkings_repository.dart
  lib/features/planner_advert/widgets/planner_advert_widget.dart
  lib/features/science_club/science_clubs_view/widgets/ensure_visible_tags.dart
  lib/l10n/app_en.arb
  lib/l10n/l10n_comment.txt
  lib/main.dart
  lib/services/pick_parking_api_service/getUseParkingApiWrapper.graphql
  lib/services/translations_service/business/translations_notifier.dart
  lib/services/translations_service/config/translations_config.dart
  lib/services/translations_service/data/data_source/business/flush_cache_drift_use_cases.dart
  lib/services/translations_service/data/data_source/client/translation_client.dart
  lib/services/translations_service/data/data_source/local/database/translation_db_singleton.dart
  lib/services/translations_service/data/data_source/local/database/translations_database.dart
  lib/services/translations_service/data/data_source/local/translations_data_source.dart
  lib/services/translations_service/data/models/supported_languages.dart
  lib/services/translations_service/data/models/translation.dart
  lib/services/translations_service/data/repository/translations_repository.dart
  lib/services/translations_service/widgets/remove_old_translations.dart
  lib/services/translations_service/widgets/text_with_translation.dart
  lib/widgets/big_preview_card.dart
  lib/widgets/dual_text_max_lines.dart
  lib/widgets/technical_message.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  macos/Runner/AppDelegate.swift
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, size/XXL

#645 fix: convert Polish time from API to UTC in sks chart model
  lib/features/sks/sks_chart/data/models/sks_chart_data.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_labels.dart
  lib/features/sks/sks_people_live/data/models/sks_user_data.dart
  lib/utils/datetime_utils.dart
Labels: size/S

#655 fix: prevent sks chart exceeding available height
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart.dart
  lib/features/sks/sks_chart/presentation/sks_chart_card.dart
  lib/features/sks/sks_chart/presentation/sks_chart_sheet.dart
Labels: size/M

#667 feat(advert): add dynamic title color
  lib/api_base/schema.graphql
  lib/features/planner_advert/repository/getPlannerAdvertContent.graphql
  lib/features/planner_advert/widgets/planner_advert_widget.dart
  lib/widgets/technical_message.dart
Labels: size/XXL

#648 feat: add possibility for the user to change apps language
  lib/features/navigation_tab_view/navigation_tab_view.dart
  lib/features/navigation_tab_view/widgets/settings_title.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/features/settings/settings.dart
  lib/features/settings/widgets/language_settings_view.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: size/L

#668 feat: add digital guide accessibility to settings screen
  lib/features/settings/settings.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: size/S

#672 chore: add headers to translations
  .env
  example.env
  lib/config/env.dart
  lib/services/translations_service/data/data_source/client/translation_client.dart
Labels: size/XS

#671 feat: change Text widget to TextWithTranslation
  lib/features/about_us_view/utils/custom_license_dialog.dart
  lib/features/about_us_view/widgets/team_section.dart
  lib/features/app_changelog/widgets/app_changelog_list.dart
  lib/features/bottom_scroll_sheet/data_list.dart
  lib/features/departments/department_detail_view/department_detail_view.dart
  lib/features/digital_guide/presentation/widgets/accessibility_information_card.dart
  lib/features/digital_guide/presentation/widgets/digital_guide_nav_link.dart
  lib/features/digital_guide/presentation/widgets/headlines_section.dart
  lib/features/digital_guide/tabs/adapted_toilets/presentation/adapted_toilet_level.dart
  lib/features/digital_guide/tabs/lifts/presentation/digital_guide_lift_detail_view.dart
  lib/features/digital_guide/tabs/lifts/presentation/digital_guide_lift_level.dart
  lib/features/digital_guide/tabs/lodge/presentation/digital_guide_lodge_expansion_tile_content.dart
  lib/features/digital_guide/tabs/micronavigation/presentation/micronavigation_detail_view.dart
  lib/features/digital_guide/tabs/rooms/presentation/digital_guide_room_detail_view.dart
  lib/features/digital_guide/tabs/rooms/presentation/digital_guide_room_level.dart
  lib/features/home_view/widgets/buildings_section/building_card.dart
  lib/features/home_view/widgets/departments_section/deparment_home_tile.dart
  lib/features/home_view/widgets/parkings_section.dart
  lib/features/parkings/parkings_view/widgets/parking_wide_tile_card.dart
  lib/features/science_club/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_club/science_clubs_filters/widgets/filter_chip.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_header.dart
  lib/features/sks/sks_menu/presentation/widgets/sks_menu_tiles.dart
  lib/widgets/detail_views/contact_section.dart
  lib/widgets/detail_views/pop_button.dart
  lib/widgets/my_alert_dialog.dart
  lib/widgets/my_expansion_tile.dart
  lib/widgets/search_box_app_bar.dart
Labels: size/L

#666 chore(digital-guide): standarize codebase
  lib/features/digital_guide/data/models/digital_guide_response.dart
  lib/features/digital_guide/presentation/widgets/accessibility_profile_card.dart
  lib/features/digital_guide/presentation/widgets/bullet_list.dart
  lib/features/digital_guide/tabs/adapted_toilets/business/adapted_toilet_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/adapted_toilets/business/adapted_toilet_accessibility_comments_menager.dart
  lib/features/digital_guide/tabs/adapted_toilets/data/models/adapted_toilet.dart
  lib/features/digital_guide/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
  lib/features/digital_guide/tabs/doors/data/model/door.dart
  lib/features/digital_guide/tabs/doors/domain/doors_accessibility_manager.dart
  lib/features/digital_guide/tabs/doors/presentation/door_view.dart
  lib/features/digital_guide/tabs/dressing_room/domain/dressing_room_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/dressing_room/presentation/digital_guide_dressing_rooms_expansion_tile.dart
  lib/features/digital_guide/tabs/entraces/bussiness/entraces_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/entraces/data/models/digital_guide_entrace.dart
  lib/features/digital_guide/tabs/entraces/presentation/entraces_detail_view.dart
  lib/features/digital_guide/tabs/information_points/business/information_point_accessibility_manager.dart
  lib/features/digital_guide/tabs/information_points/models/digital_guide_information_points.dart
  lib/features/digital_guide/tabs/information_points/widgets/information_point_widget.dart
  lib/features/digital_guide/tabs/lifts/business/lifts_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/lifts/data/models/digital_guide_lift.dart
  lib/features/digital_guide/tabs/lifts/presentation/digital_guide_lift_detail_view.dart
  lib/features/digital_guide/tabs/rooms/business/rooms_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/rooms/platforms/business/room_platforms_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/rooms/stairs/business/room_stairs_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/corridors_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/railings_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/ramps_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/stairs_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/stairway_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/business/toilets_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/structure/presentation/views/corridor_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/railings_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/ramps_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/region_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairs_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/stairway_view.dart
  lib/features/digital_guide/tabs/structure/presentation/views/toilets_view.dart
  lib/features/digital_guide/tabs/surrounding/business/surroundings_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/surrounding/data/models/surrounding_response.dart
  lib/features/digital_guide/tabs/transportation/business/non_public_transportation_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/transportation/business/public_transportation_accessibility_comments_manager.dart
  lib/features/digital_guide/tabs/transportation/data/models/digital_guide_transportation.dart
  lib/features/digital_guide/tabs/transportation/presentation/transportation_detail_view.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/utils/type_converter.dart
Labels: size/XXL

#662 feat: add status to graphql and show only active circles
  lib/features/science_club/science_clubs_view/repository/getScienceClubs.graphql
  lib/features/science_club/science_clubs_view/repository/science_clubs_repository.dart
Labels: size/S
