Repository Solvro/mobile-topwr, pull requests merged in 2025-04, with the labels that each got.

#674 fix: organize arb files, add metadata/types and fully translate english strings
  l10n.yaml
  lib/features/digital_guide/tabs/entraces/bussiness/entraces_accessibility_comments_manager.dart
  lib/features/navigator/app_router.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/l10n/l10n_comment.txt
  lib/l10n/untranslated_messages.txt
  lib/services/translations_service/data/data_source/business/flush_cache_drift_use_cases.dart
  lib/services/translations_service/widgets/remove_old_translations.dart
Labels: size/XXL

#675 fix: translations fixes
  .github/workflows/flutter_ci.yaml
  README.md
  assets/svg/settings.svg
  lib/config/nav_bar_config.dart
  lib/features/about_us_view/widgets/app_version.dart
  lib/features/about_us_view/widgets/description_section.dart
  lib/features/digital_guide/presentation/widgets/accessibility_information_card.dart
  lib/features/digital_guide/presentation/widgets/bullet_list.dart
  lib/features/digital_guide/tabs/evacuation/evacuation_widget.dart
  lib/features/digital_guide/tabs/micronavigation/presentation/micronavigation_detail_view.dart
  lib/features/digital_guide_objects/presentation/digital_g_objects_featers_list.dart
  lib/features/guide_detail_view/guide_detail_view.dart
  lib/features/guide_detail_view/utils/get_the_latest_date.dart
  lib/features/guide_detail_view/widgets/faq_expansion_tile.dart
  lib/features/science_club/science_club_detail_view/science_club_detail_view.dart
  lib/features/science_club/science_club_detail_view/widgets/about_us_section.dart
  lib/features/science_club/science_clubs_view/widgets/ensure_visible_tags.dart
  lib/features/settings/settings_view.dart
  lib/features/settings/widgets/language_settings_dialog.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_labels.dart
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_line_touch_data.dart
  lib/features/sks/sks_menu/presentation/sks_menu_screen.dart
  lib/features/sks/sks_menu/presentation/widgets/sks_menu_header.dart
  lib/features/sks/sks_menu/presentation/widgets/sks_menu_tiles.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/services/translations_service/data/repository/translations_repository.dart
  lib/services/translations_service/widgets/my_html_widget_with_translation.dart
  lib/services/translations_service/widgets/rich_text_with_translation.dart
  lib/utils/context_extensions.dart
  lib/utils/datetime_utils.dart
  lib/widgets/big_preview_card.dart
  lib/widgets/date_chip.dart
  lib/widgets/detail_views/contact_section.dart
  lib/widgets/detail_views/detail_view_app_bar.dart
  lib/widgets/dual_text_max_lines.dart
  lib/widgets/my_point_widget.dart
  lib/widgets/search_box_app_bar.dart
Labels: bug, enhancement, size/L

#677 fix(map): map tile layer caching
  .github/workflows/pr_title_ci.yaml
  lib/config/map_view_config.dart
  lib/features/map_view/data/cache.dart
  lib/features/map_view/widgets/map_widget.dart
  lib/features/splash_screen/splash_screen_controller.dart
  pubspec.yaml
Labels: bug, size/M

#679 fix: animation shown when returning from tab
  lib/features/navigator/app_router.dart
  lib/widgets/horizontal_symmetric_safe_area.dart
Labels: bug, size/S

#669 feat: Add slider to building view
  .gitignore
  lib/features/bottom_scroll_sheet/sheet_layout_scheme.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: size/L

#673 feat: rest api in guide
  .env
  example.env
  lib/api_base_rest/cache/cache_manager.dart
  lib/api_base_rest/shared_models/image_data.dart
  lib/config/env.dart
  lib/features/guide_detail_view/data/models/guide_details.dart
  lib/features/guide_detail_view/data/repository/guide_details_repository.dart
  lib/features/guide_detail_view/guide_detail_view.dart
  lib/features/guide_detail_view/repository/getGuideDetails.graphql
  lib/features/guide_detail_view/repository/guide_detail_view_repository.dart
  lib/features/guide_detail_view/utils/get_the_latest_date.dart
  lib/features/guide_view/data/models/guide_data.dart
  lib/features/guide_view/data/repository/guide_repository.dart
  lib/features/guide_view/guide_view.dart
  lib/features/guide_view/guide_view_controller.dart
  lib/features/guide_view/repository/getGuide.graphql
  lib/features/guide_view/repository/guide_repository.dart
  lib/features/guide_view/widgets/guide_tile.dart
  lib/features/home_view/keep_alive_home_view_providers.dart
  lib/features/home_view/widgets/news_section.dart
  lib/features/navigator/utils/navigation_commands.dart
Labels: enhancement, size/L

#688 fix: update TRANSLATE_API_TOKEN
  .env
Labels: bug, size/XS

#690 fix: update scientific circles terminology in English and Polish
  lib/config/nav_bar_config.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
Labels: bug, chore, size/S

#681 refactor: change from watch to read in parkings
  lib/features/parkings/parkings_view/widgets/parking_favourite.dart
Labels: size/XS

#693 fix(parkings): distinct chart labels
  lib/config/ui_config.dart
  lib/features/parkings/parking_chart/widgets/chart_widget.dart
Labels: size/S

#692 Chore/replace graphql with rest for repartments
  lib/config/ui_config.dart
  lib/features/departments/department_detail_view/data/models/department_details.dart
  lib/features/departments/department_detail_view/data/repository/department_details_repository.dart
  lib/features/departments/department_detail_view/data/utils/department_details_extension.dart
  lib/features/departments/department_detail_view/presentation/department_detail_view.dart
  lib/features/departments/department_detail_view/presentation/widgets/field_of_study_expansion_tile.dart
  lib/features/departments/department_detail_view/presentation/widgets/field_of_study_tile.dart
  lib/features/departments/department_detail_view/presentation/widgets/fields_of_study_section.dart
  lib/features/departments/department_detail_view/presentation/widgets/science_clubs_section.dart
  lib/features/departments/department_detail_view/presentation/widgets/sliver_header_section.dart
  lib/features/departments/department_detail_view/presentation/widgets/view_loading.dart
  lib/features/departments/department_detail_view/repository/department_details_repository.dart
  lib/features/departments/department_detail_view/repository/getDepartmentDetails.graphql
  lib/features/departments/department_detail_view/utils/address_formatter.dart
  lib/features/departments/department_detail_view/utils/department_details_gradient.dart
  lib/features/departments/department_detail_view/utils/fields_of_studies.dart
  lib/features/departments/departments_view/data/models/department.dart
  lib/features/departments/departments_view/data/repository/departments_repository.dart
  lib/features/departments/departments_view/data/utils/departments_extensions.dart
  lib/features/departments/departments_view/departments_view.dart
  lib/features/departments/departments_view/departments_view_controllers.dart
  lib/features/departments/departments_view/repository/departments_repository.dart
  lib/features/departments/departments_view/repository/getDepartments.graphql
  lib/features/departments/departments_view/widgets/department_card.dart
  lib/features/home_view/keep_alive_home_view_providers.dart
  lib/features/home_view/widgets/departments_section/deparment_home_tile.dart
  lib/features/home_view/widgets/departments_section/departments_section.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/navigation_controller.dart
  lib/features/navigator/utils/navigation_commands.dart
  lib/features/science_club/science_clubs_filters/filters_controller.dart
  lib/features/science_club/science_clubs_filters/filters_search_controller.dart
  lib/features/science_club/science_clubs_filters/widgets/departments_wrap.dart
  lib/features/science_club/science_clubs_view/safe_load_initial_repos.dart
  lib/features/science_club/science_clubs_view/science_clubs_view.dart
Labels: size/L

#700 feat(home-screen-banner): adjust paddings #661
  lib/features/planner_advert/widgets/planner_advert_widget.dart
Labels: size/XS

#702 feat(parking): adjust padding #660
  lib/config/map_view_config.dart
  lib/features/map_view/widgets/map_widget.dart
Labels: size/XS

#701 feat: rest in about us
  lib/api_base_rest/shared_models/social_links_data.dart
  lib/features/about_us_view/about_us_view.dart
  lib/features/about_us_view/data/models/about_us.dart
  lib/features/about_us_view/data/models/about_us_data.dart
  lib/features/about_us_view/data/models/team_members_data.dart
  lib/features/about_us_view/data/models/versions_data.dart
  lib/features/about_us_view/data/repository/about_us_repository.dart
  lib/features/about_us_view/models/about_us_details.dart
  lib/features/about_us_view/models/member_data.dart
  lib/features/about_us_view/repository/about_us_repository.dart
  lib/features/about_us_view/repository/getAboutUsDetails.graphql
  lib/features/about_us_view/widgets/team_section.dart
Labels: enhancement, size/L

#704 feat(translation): add dialog on the first launch
  lib/api_base/translations/temp_graphql_translate.dart
  lib/api_base_rest/translations/translate.dart
  lib/config/translations_config.dart
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/red_dialog.dart
  lib/features/navigator/root_view.dart
  lib/features/settings/widgets/language_settings_dialog.dart
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/services/translations_service/data/preferred_lang_repository.dart
  lib/services/translations_service/hooks/use_language_dialog.dart
  lib/services/translations_service/widgets/show_first_dialog.dart
Labels: enhancement, size/L
