Repository Solvro/mobile-topwr, pull requests merged in 2025-07, with the labels that each got.

#775 feat: migrate changelog to REST API
  lib/features/app_changelog/app_changelog.dart
  lib/features/app_changelog/data/models/changelog.dart
  lib/features/app_changelog/data/repository/local_changelog_repository.dart
  lib/features/app_changelog/data/repository/my_changelog_repository.dart
  lib/features/app_changelog/repository/changelog_repository.dart
  lib/features/app_changelog/repository/get_changelog.graphql
  lib/features/app_changelog/show_changelog.dart
  lib/features/app_changelog/widgets/app_changelog_list.dart
Labels: enhancement, size/L

#777 fix/add field of studies enum type
  lib/features/departments/department_detail_view/data/models/department_details.dart
  lib/features/departments/department_detail_view/data/models/studies_type.dart
  lib/features/departments/department_detail_view/data/utils/department_details_extension.dart
Labels: size/M

#778 fix: add unwaited microtask util
  lib/api_base/cache/remote_flush/presentation/flush_cache_remotely_widget.dart
  lib/features/app_changelog/update_changelog_wrapper.dart
  lib/features/bottom_scroll_sheet/hooks/use_initial_active_id.dart
  lib/features/map_view/controllers/bottom_sheet_controller.dart
  lib/features/navigator/navigation_stack.dart
  lib/features/science_club/science_clubs_filters/hooks/use_initial_filter_ids.dart
  lib/hooks/use_semantics_service_on_changed_value.dart
  lib/services/translations_service/widgets/remove_old_translations.dart
  lib/utils/unwaited_microtask.dart
  lib/widgets/my_error_widget.dart
Labels: chore, size/M

#782 fix: fix status bar for accessibility dialog
  lib/features/digital_guide/tabs/accessibility_dialog/presentation/accessibility_dialog.dart
Labels: size/XS

#790 chore: maitainance stuff
  lib/features/sks/sks_chart/presentation/chart_elements/sks_chart_legend.dart
  lib/widgets/loading_widgets/shimmer_loading.dart
  linux/flutter/generated_plugins.cmake
  pubspec.yaml
  windows/flutter/generated_plugins.cmake
Labels: chore, size/L

#791 fix(navigation): new navigation flow (again)
  lib/features/bottom_nav_bar/bottom_nav_bar.dart
  lib/features/bottom_scroll_sheet/hooks/use_initial_active_id.dart
  lib/features/navigator/app_router.dart
  lib/features/navigator/navigation_controller.dart
  lib/features/navigator/root_view.dart
  lib/features/navigator/utils/android_pop_bug_workaround.dart
Labels: size/L
